// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ObliKot2r2.Models;

#nullable disable

namespace ObliKot2r2.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250808080308_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ObliKot2r2.Models.Area", b =>
                {
                    b.Property<int>("IdArea")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdArea"));

                    b.Property<string>("IdAnother")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("IdAreaSAP")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("IdSubdivision")
                        .HasColumnType("int");

                    b.Property<string>("NameArea")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<byte[]>("ObjArea")
                        .HasColumnType("varbinary(max)");

                    b.HasKey("IdArea");

                    b.HasIndex("IdSubdivision");

                    b.ToTable("Areas");
                });

            modelBuilder.Entity("ObliKot2r2.Models.GasMeasuringObject", b =>
                {
                    b.Property<long>("IdGMO")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdGMO"));

                    b.Property<string>("IdAnother")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("IdArea")
                        .HasColumnType("int");

                    b.Property<string>("IdGmoSAP")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("NameGMO")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<byte[]>("ObjGMO")
                        .HasColumnType("varbinary(max)");

                    b.HasKey("IdGMO");

                    b.HasIndex("IdArea");

                    b.ToTable("GasMeasuringObjects");
                });

            modelBuilder.Entity("ObliKot2r2.Models.MeasuringPipe", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("GmoId")
                        .HasColumnType("bigint");

                    b.Property<string>("IdAnother")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("NameMPipe")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<byte[]>("ObjMPipe")
                        .HasColumnType("varbinary(max)");

                    b.HasKey("Id");

                    b.HasIndex("GmoId");

                    b.ToTable("MeasuringPipes");
                });

            modelBuilder.Entity("ObliKot2r2.Models.Philia", b =>
                {
                    b.Property<int>("IdPhilia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPhilia"));

                    b.Property<string>("IdAnother")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("IdPhiliaSAP")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("NamePhilia")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte[]>("ObjPhilia")
                        .HasColumnType("varbinary(max)");

                    b.HasKey("IdPhilia");

                    b.ToTable("Philia");
                });

            modelBuilder.Entity("ObliKot2r2.Models.PointIO", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateBegin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateEnd")
                        .HasColumnType("datetime2");

                    b.Property<string>("EIC")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("IdAnother")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<long>("IdGMO")
                        .HasColumnType("bigint");

                    b.Property<string>("IdPointIOSAP")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("IdTypePointIO")
                        .HasColumnType("int");

                    b.Property<string>("NamePointIO")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("IdGMO");

                    b.HasIndex("IdTypePointIO");

                    b.ToTable("PointIOs");
                });

            modelBuilder.Entity("ObliKot2r2.Models.PointIOType", b =>
                {
                    b.Property<int>("IdTypePointIO")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTypePointIO"));

                    b.Property<string>("NameTypePointIO")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdTypePointIO");

                    b.ToTable("PointIOTypes");

                    b.HasData(
                        new
                        {
                            IdTypePointIO = 1,
                            NameTypePointIO = "Точка входу"
                        },
                        new
                        {
                            IdTypePointIO = 2,
                            NameTypePointIO = "Точка виходу"
                        },
                        new
                        {
                            IdTypePointIO = 3,
                            NameTypePointIO = "Точка входу-виходу"
                        },
                        new
                        {
                            IdTypePointIO = 4,
                            NameTypePointIO = "Віртуальна точка входу"
                        },
                        new
                        {
                            IdTypePointIO = 5,
                            NameTypePointIO = "Віртуальна точка виходу"
                        },
                        new
                        {
                            IdTypePointIO = 6,
                            NameTypePointIO = "Віртуальна точка входу-виходу"
                        });
                });

            modelBuilder.Entity("ObliKot2r2.Models.Subdivision", b =>
                {
                    b.Property<int>("IdSubdivision")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdSubdivision"));

                    b.Property<string>("IdAnother")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("IdPhilia")
                        .HasColumnType("int");

                    b.Property<string>("IdSubdivisionSAP")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("NameSubdivision")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<byte[]>("ObjSubdivision")
                        .HasColumnType("varbinary(max)");

                    b.HasKey("IdSubdivision");

                    b.HasIndex("IdPhilia");

                    b.ToTable("Subdivisions");
                });

            modelBuilder.Entity("ObliKot2r2.Models.Area", b =>
                {
                    b.HasOne("ObliKot2r2.Models.Subdivision", "Subdivision")
                        .WithMany("Areas")
                        .HasForeignKey("IdSubdivision")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subdivision");
                });

            modelBuilder.Entity("ObliKot2r2.Models.GasMeasuringObject", b =>
                {
                    b.HasOne("ObliKot2r2.Models.Area", "Area")
                        .WithMany()
                        .HasForeignKey("IdArea")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Area");
                });

            modelBuilder.Entity("ObliKot2r2.Models.MeasuringPipe", b =>
                {
                    b.HasOne("ObliKot2r2.Models.GasMeasuringObject", "GMO")
                        .WithMany("MeasuringPipes")
                        .HasForeignKey("GmoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GMO");
                });

            modelBuilder.Entity("ObliKot2r2.Models.PointIO", b =>
                {
                    b.HasOne("ObliKot2r2.Models.GasMeasuringObject", "GMO")
                        .WithMany()
                        .HasForeignKey("IdGMO")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ObliKot2r2.Models.PointIOType", "PointIOType")
                        .WithMany("PointIOs")
                        .HasForeignKey("IdTypePointIO")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GMO");

                    b.Navigation("PointIOType");
                });

            modelBuilder.Entity("ObliKot2r2.Models.Subdivision", b =>
                {
                    b.HasOne("ObliKot2r2.Models.Philia", "Philia")
                        .WithMany("Subdivisions")
                        .HasForeignKey("IdPhilia")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Philia");
                });

            modelBuilder.Entity("ObliKot2r2.Models.GasMeasuringObject", b =>
                {
                    b.Navigation("MeasuringPipes");
                });

            modelBuilder.Entity("ObliKot2r2.Models.Philia", b =>
                {
                    b.Navigation("Subdivisions");
                });

            modelBuilder.Entity("ObliKot2r2.Models.PointIOType", b =>
                {
                    b.Navigation("PointIOs");
                });

            modelBuilder.Entity("ObliKot2r2.Models.Subdivision", b =>
                {
                    b.Navigation("Areas");
                });
#pragma warning restore 612, 618
        }
    }
}
